@host=http://localhost:5136
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YTQyNWZmZC1jMzc3LTRjYmItOGVmOC00MGM5Y2Q0ODAwMjkiLCJnaXZlbl9uYW1lIjoiQW5pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGluYmFuZCIsImp0aSI6IjI0MzI3NDI5LTg0MDItNGJmYy05ODA3LTU1OTg1NzU1ZjMwOSIsImV4cCI6MTY5MDY2NjY4NiwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.l9jHWir00OXd125DFCPwV3k4GY9W5DAABabXSDY5P68
@hostId=6B29FC40-CA47-1067-B31D-00DD010662DA
POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}