@host=http://localhost:5136
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NzZlMjk1My00ZjAzLTRlNmYtOWJmMy1mOTExNGM5ZGI1ZWYiLCJnaXZlbl9uYW1lIjoiQW5pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGluYmFuZCIsImp0aSI6IjY1NTdmMjQ2LWIyZGQtNDZmYy05ODViLWMwZTAzMmQxMDM4ZCIsImV4cCI6MTY5MDQwMjI2MCwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.uziUeh96eB-Wf7jVzjI2pd2Ov-IppXxOeYp4dYtzdtU
@hostId=asfgd
POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "averageRating": 4.5,
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ],
    "hostId": { "value": "00000000-0000-0000-0000-000000000000" },
    "createdDateTime": "2020-01-01T00:00:00.0000000Z",
    "updatedDateTime": "2020-01-01T00:00:00.0000000Z"
}