@host=http://localhost:5136
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YjM0MzllMC00YTE5LTRmOWQtYTkzMi0wYWUxMmVlN2ZmZDUiLCJnaXZlbl9uYW1lIjoiQW5pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGluYmFuZCIsImp0aSI6ImY3OWJmZWQ2LWJhYWMtNGFkNC04NzYyLTg2OWZhODliZGZhMiIsImV4cCI6MTY5MDYzMTc4OCwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.Jebep-DxO1smD_GF2ja7qMGy3BsPQ_U6qxcT2P_FxNA
@hostId=6B29FC40-CA47-1067-B31D-00DD010662DA
POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}